### ISSUE TITLE
Add JDK 9+ / modules support

### ISSUE THREAD

**Issue by skjolber** [auth0/jwks-rsa-java#76] opened 2019-11-25 09:46 UTC
### Describe the problem you'd like to have solved

Using this library deterministicly as an dependency in a JDK 9+ project; fixing the module name.

### Describe the ideal solution

Multi-release jar.

## Alternatives and current work-arounds

[Automatic-Module-Name](https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers) goes a long way.

**Comment by skjolber** [comment] 2020-02-23 15:08
Ping

**Comment by skjolber** [comment] 2020-05-23 20:44
Ping

**Comment by lbalmaceda** [comment] 2020-07-15 19:18
@skjolber apologies for the delay. Do you have a [small sample app](https://stackoverflow.com/help/minimal-reproducible-example) where we can test this? 

We're not targetting JDK9 as a minimum version but would like to understand the use case a bit more. What do you mean by using it deterministically? 

And, separate from that ask, you posted a link to a workaround that involves adding the module name as part of the jar's manifest file. That would involve a one-line change [here](https://github.com/auth0/oss-library-gradle-plugin/blob/429ca29ecc1439117aa0f858bfd3c462277c3543/src/main/groovy/com/auth0/gradle/oss/LibraryPlugin.groovy#L61) to our understanding. We would still need to understand what the module name should be in that case. From the link you shared, looks like a "package" + "project". e.g. `com.auth0.jwks-rsa.lib`.

**Comment by skjolber** [comment] 2020-07-15 21:11
The 'deterministically part' was as follows: Maven creates a module name from the artifact name, if none is declared. Which is all fine for standalone applications, but this kind of 'local context' does not work well when writing a library; the risk is that there will be collisions or unresolvable imports downstream (i.e. in the 'global context').

I do not have an example app. But you want to create an maven or gradle app which uses the module system, and import your library as a dependency. Then check that the app can not access the library classes before adding an import statement in the app module-info.

I think for a single-artifact library like this, `com.auth0.jwks-rsa` is fair. And perhaps this is a good time to create a global approach for all your Gradle libraries, where you create real multi-release jars, instead of Automatic-Module-Name. Just put the module-info in a seperate source directory, and find a plugin which compiles and packages it into the release. At least that is what I'm doing with my maven projects.

**Comment by jimmyjames** [comment] 2020-09-14 17:42
Closing this issue to track it with https://github.com/auth0/oss-library-gradle-plugin/issues/19

**Closed by jimmyjames** 2020-09-14 17:42 UTC
